---
- name: Create a pretalx user
  user:
    name: "{{ pretalx_system_user }}"
    state: present
  tags:
    - pretalx

- name: Do things as pretalx user
  tasks:
  - name: Install pretalx dependencies
    pip:
      name: "{{ item }}"
      executable: pip3
      extra_args: --user
      state: latest
    with_items:
      - gunicorn
      - pip
      - setuptools
      - wheel

  - name: Install pretalx (latest)
    pip:
      name: pretalx
      executable: pip3
      extra_args: --user
      state: latest
    notify:
      - Restart pretalx service
      - Run pretalx migrations
      - Collect static pretalx files
      - Compress static pretalx files
      - Compile pretalx messages
    when: (pretalx_version == 'latest')

  - name: Install pretalx (versioned)
    pip:
      name: pretalx
      executable: pip3
      extra_args: --user
      version: "{{ pretalx_version }}"
    notify:
      - Restart pretalx service
      - Run pretalx migrations
      - Collect static pretalx files
      - Compress static pretalx files
      - Compile pretalx messages
    when: (pretalx_version != 'latest')

  - name: Configure pretalx
    template:
      src: pretalx.cfg.j2
      dest: ~/.pretalx.cfg
    notify:
      - Restart pretalx service
      - Run pretalx migrations
      - Collect static pretalx files
      - Compress static pretalx files
      - Compile pretalx messages
  become_user: "{{ pretalx_system_user }}"
  tags:
    - pretalx

- name: Install systemd socket
  template:
    src: pretalx.socket
    dest: /etc/systemd/system/pretalx_{{ pretalx_instance_identifier }}.socket
  notify:
    - Reload systemd services
    - Restart pretalx socket
  tags:
    - pretalx

- name: Install systemd service
  template:
    src: pretalx.service.j2
    dest: /etc/systemd/system/pretalx@.service
  notify:
    - Restart pretalx service
  tags:
    - pretalx

- name: Start pretalx socket
  service:
    name: pretalx{{ pretalx_instance_identifier }}.socket
    state: started
    enabled: true
  tags:
    - pretalx

- name: Start systemd service
  service:
    name: pretalx@{{ pretalx_instance_identifier }}
    state: started
    enabled: true
  tags:
    - pretalx
