---
- name: Create a pretalx user
  user:
    name: pretalx
    state: present
  tags:
    - pretalx

- name: Install pretalx dependencies
  pip:
    name: "{{ item }}"
    executable: pip3
    extra_args: --user
    state: latest
  with_items:
    - gunicorn
    - pip
    - setuptools
    - wheel
  become_user: pretalx
  tags:
    - pretalx

- name: Install pretalx
  pip:
    name: git+https://github.com/pretalx/pretalx#subdirectory=src/&egg=pretalx
    executable: pip3
    extra_args: --user
    state: latest  # TODO: move to 'latest' or fixed version once pretalx has versioning
  become_user: pretalx
  notify:
    - Restart pretalx service
    - Run pretalx migrations
    - Collect static pretalx files
    - Compress static pretalx files
    - Compile pretalx messages
  tags:
    - pretalx

- name: Configure pretalx
  template:
    src: pretalx.cfg.j2
    dest: ~/.pretalx.cfg
  become_user: pretalx
  notify:
    - Restart pretalx service
    - Run pretalx migrations
    - Collect static pretalx files
    - Compress static pretalx files
    - Compile pretalx messages
  tags:
    - pretalx

- name: Install systemd socket
  copy:
    src: pretalx.socket
    dest: /etc/systemd/system/pretalx.socket
  notify:
    - Restart pretalx socket
  tags:
    - pretalx

- name: Install systemd service
  copy:
    src: pretalx.service
    dest: /etc/systemd/system/pretalx.service
  notify:
    - Restart pretalx service
  tags:
    - pretalx

- name: Start pretalx socket
  service:
    name: pretalx.socket
    state: started
    enabled: true
  tags:
    - pretalx

- name: Start systemd service
  service:
    name: pretalx
    state: started
    enabled: true
  tags:
    - pretalx
