---
- name: Install Python 3.6
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - python

- name: Install other dependencies
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - sqlite
