---
- name: Install Python 3.6
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - python
  tags:
    - pretalx

- name: Install other dependencies
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - sqlite
  tags:
    - pretalx
