---
- name: Reload systemd services
  systemd:
    daemon_reload: yes

- name: Restart redis
  service:
    name: redis
    state: restarted

- name: Reload nginx
  service:
    name: nginx
    state: reloaded

- name: Restart pretalx service
  service:
    name: pretalx@{{ pretalx_instance_identifier }}
    state: restarted

- name: Restart worker service
  service:
    name: pretalx-worker@{{ pretalx_instance_identifier }}
    state: restarted

- name: Restart pretalx socket
  service:
    name: pretalx@{{ pretalx_instance_identifier }}.socket
    state: restarted

- name: Run pretalx migrations
  command: python -m pretalx migrate
  become: true
  become_user: "{{ pretalx_system_user }}"

- name: Collect static pretalx files
  command: python -m pretalx collectstatic --noinput
  become: true
  become_user: "{{ pretalx_system_user }}"

- name: Compress static pretalx files
  command: python -m pretalx compress
  become: true
  become_user: "{{ pretalx_system_user }}"

- name: Compile pretalx messages
  command: python -m pretalx compilemessages
  become: true
  become_user: "{{ pretalx_system_user }}"
